[WIP] PT-BR Localization
gervasiocaj/8values.github.io pull request #1
Opened 2017-04-27 00:48 UTC by JoaoGFarias

- [x] ideologies.json
- [x] instructions.json
- [x] matches.json
- [ ] questions.json
- [x] quiz.json
- [ ] translation.json

2017-04-27 19:24 UTC, dserodio requested changes
Sugiro algumas correções e alterações

2017-04-27 19:24 UTC, dserodio commented on locales/pt/ideologies.json
> +    "ideo24": "Totalitarianismo Nacionalista",
Totalitarismo: http://michaelis.uol.com.br/busca?r=0&f=0&t=0&palavra=totalitarismo

2017-04-27 19:24 UTC, dserodio commented on locales/pt/ideologies.json
> +    "ideo29": "Anarchismo Religioso",
Anarquismo: http://michaelis.uol.com.br/busca?r=0&f=0&t=0&palavra=anarquismo

2017-04-27 19:24 UTC, dserodio commented on locales/pt/ideologies.json
> +    "ideo48": "Anarchismo de Mercado",
Anarquismo de Mercado

2017-04-27 19:24 UTC, dserodio commented on locales/pt/ideologies.json
> +    "ideo47": "Capitalismo LIbertário",
s/LI/Li/

2017-04-27 19:24 UTC, dserodio commented on locales/pt/matches.json
> +    "govt": ["Anarchista","Libertário","Liberal","Moderado","Estatista","Autoritário","Totalitarista"],
Anarquista… Estadista

2017-04-27 19:24 UTC, dserodio commented on locales/pt/matches.json
> +    "govt": ["Anarchista","Libertário","Liberal","Moderado","Estatista","Autoritário","Totalitarista"],
Compare http://michaelis.uol.com.br/busca?r=0&f=0&t=0&palavra=estadista e 
http://michaelis.uol.com.br/busca?r=0&f=0&t=0&palavra=estatista

2017-04-27 19:24 UTC, dserodio commented on locales/pt/translation.json
> +	"faq_whatis_answer": "8values é, em essência, um questionário político que tenta indicar porcentagens para oito diferentes valores políticos. Você será apresentado a uma afirmação e, então, você res
s/tuas reposta/tuas respostas/

s/um porcentagem/uma porcentagem/

2017-04-27 19:24 UTC, dserodio commented on locales/pt/translation.json
> +	"faq_match": "O que significa &quot;Perfil mais Próximo&quot; ao final dos resultado?",
s/dos resultado/do resultado/

2017-04-27 19:24 UTC, dserodio commented on locales/pt/translation.json
> +	"faq_values_answer": "Existem quatro eixos - Econômico, Diplomático, Estado, e Sociedade - e cada um tem dois valores opostos assinalados para eles. Estes são:",
Creio que _assinalados_ não está correto, mas não sei se o melhor seria _atribuídos_ ou _designados_

2017-04-27 19:24 UTC, dserodio commented on locales/pt/translation.json
> +	"faq_scores_answer": "¯\\_(ツ)_/¯<br/>Se você tem alguma sugestão ou crítica construtiva, sinta-se a vontade para enviar um e-mail para eightvalues@gmail.com",
Creio que o correto é "à vontade"

2017-04-27 19:29 UTC, renanpvaz commented on locales/pt/ideologies.json
> +    "ideo1": "Anarco-comunismo",
Acredito que esta e algumas outras ideologias não possuem mais o hífen [de acordo com a regra](http://www.infoescola.com/portugues/uso-do-hifen-descomplicado/).

2017-04-28 19:02 UTC, gervasiocaj commented on locales/pt/translation.json
> +	"faq_whatis_answer": "8values é, em essência, um questionário político que tenta indicar porcentagens para oito diferentes valores políticos. Você será apresentado a uma afirmação e, então, você res
Usaremos a notação `concordo fortemente` ou `concordo plenamente`? O tópico 3.5 [desse artigo](https://www.maxwell.vrac.puc-rio.br/18195/18195_4.PDF) fala um pouco sobre isso.

2017-04-28 19:07 UTC, gervasiocaj requested changes
Precisamos corrigir de acordo com as sugestões de @dserodio e @renanpvaz 
Revisar de acordo com 8values/8values.github.io@cb41063

2017-05-05 13:28 UTC, merged